# Generated by Django 4.2.5 on 2023-09-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
                ('q5', models.IntegerField(default=0)),
                ('q6', models.IntegerField(default=0)),
                ('q7', models.IntegerField(default=0)),
                ('q8', models.IntegerField(default=0)),
                ('q9', models.IntegerField(default=0)),
                ('q10', models.IntegerField(default=0)),
            ],
        ),
    ]
